version: "3"

services:
  client:
    image: totomadne/time-manager-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  server:
    image: totomadne/time-manager-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=ecto://postgres:y5Pbd9!zJ@database/server_dev
      - SECRET_KEY_BASE=PIka98wGA3efhWhEiRTnJAGXdDlf9P9CqeaweKg8vMSCIY0+fYJWDlavmq88kMkg
      - DBUSER=postgres
      - DBPASSWORD=y5Pbd9!zJ
      - DBDATABASE=server_dev
      - DBPORT=5432
      - DBHOST=database
    ports:
      - "4000:4000"
    depends_on:
      - database
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=y5Pbd9!zJ
      - POSTGRES_DB=server_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
